#!/bin/bash
#LATENCY RUNS
#20, 50, 80 drives, sequence 32
#python3 main.py -nd 80  -seq 32  -bs 512 -tt 1 -name seq_32_80_label_0 -lff 1 -mdimsi 0 -l 0 -lr 1e-4
##20, 50, 80 drives, sequence 64
#python3 main.py -nd 80 -seq 64  -bs 512 -tt 1 -name seq_64_80_label_0 -lff 1 -mdimsi 0 -l 0 -lr 1e-4
##20, 50, 80 drives, sequence 128
#python3 main.py -nd 80 -seq 128  -bs 512 -tt 1 -name seq_128_80_label_0 -lff 1 -mdimsi 0 -l 0 -lr 1e-4


#Prepare Dataset for testing
python3 main.py -nd 80 -seq 32 -bs 512 -tt 1 -name seq_32_80_label_2_test -mso 0 -lff 0 -mdimsi 0 -l 2 -pds 0

#command for testing
python3 main.py -nd 80 -seq 32 -bs 512 -tt 0 -name seq_32_80_label_2_test -mso 0 -lff 1 -mdimsi 0 -l 2 -pds 0
