#!/bin/bash

#Prepare Dataset
python3 main.py -nd 80 -seq 32 -bs 512 -tt 1 -name seq_32_80_label_2 -lff 0 -mdimsi 0 -l 2 -pds 1
python3 main.py -nd 80 -seq 64 -bs 512 -tt 1 -name seq_64_80_label_2 -lff 0 -mdimsi 0 -l 2 -pds 1
python3 main.py -nd 80 -seq 128 -bs 512 -tt 1 -name seq_128_80_label_2 -lff 0 -mdimsi 0 -l 2 -pds 1

