#!/bin/bash
#CREATE DATASETS
##20, 50, 80 drives, sequence 32 #under sampling
#python3 main.py -nd 20 -ndtrain 400 -seq 32 -nnsize 32 -nnlayers 2 -balanced 1 -bs 256 -tt 0 -name seq_32_20_label_0 -mso 0 -lff 0 -mdimsi 0 -l 0
#python3 main.py -nd 80 -ndtrain 400 -seq 32 -nnsize 32 -nnlayers 2 -balanced 1 -bs 256 -tt 0 -name seq_32_80_label_0 -mso 0 -lff 0 -mdimsi 0 -l 0
#
###20, 50, 80 drives, sequence 32 #under sampling
#python3 main.py -nd 20 -ndtrain 400 -seq 64 -nnsize 32 -nnlayers 2 -balanced 1 -bs 256 -tt 0 -name seq_64_20_label_0 -mso 0 -lff 0 -mdimsi 0 -l 0
#python3 main.py -nd 80 -ndtrain 400 -seq 64 -nnsize 32 -nnlayers 2 -balanced 1 -bs 256 -tt 0 -name seq_64_80_label_0 -mso 0 -lff 0 -mdimsi 0 -l 0
#
###20, 50, 80 drives, sequence 32 #under sampling
#python3 main.py -nd 20 -ndtrain 400 -seq 128 -nnsize 32 -nnlayers 2 -balanced 1 -bs 256 -tt 0 -name seq_128_20_label_0 -mso 0 -lff 0 -mdimsi 0 -l 0
#python3 main.py -nd 80 -ndtrain 400 -seq 128 -nnsize 32 -nnlayers 2 -balanced 1 -bs 256 -tt 0 -name seq_128_80_label_0 -mso 0 -lff 0 -mdimsi 0 -l 0

#LOAD DATASETS seq 64, Drive 20,50,80 batch size 128
#python3 main.py -nd 20 -ndtrain 400 -seq 64 -nnsize 32 -nnlayers 2 -balanced 1 -bs 128 -tt 1 -name seq_64_20_all_imsi -mso 0 -lff 1 -mdimsi 0



##20, 50, 80 drives, sequence 32 #under sampling
python3 main.py -nd 20  -seq 32  -bs 128 -tt 1 -name seq_32_20_label_0 -lff 1 -mdimsi 0 -l 0 -lr 1e-3
python3 main.py -nd 80  -seq 32  -bs 512 -tt 1 -name seq_32_80_label_0 -lff 1 -mdimsi 0 -l 0 -lr 1e-3

##20, 50, 80 drives, sequence 64 #under sampling
python3 main.py -nd 20 -seq 64  -bs 128 -tt 1 -name seq_64_20_label_0 -lff 1 -mdimsi 0 -l 0 -lr 1e-3
python3 main.py -nd 80 -seq 64  -bs 512 -tt 1 -name seq_64_80_label_0 -lff 1 -mdimsi 0 -l 0 -lr 1e-3

##20, 50, 80 drives, sequence 128 #under sampling
python3 main.py -nd 20 -seq 128  -bs 128 -tt 1 -name seq_128_20_label_0 -lff 1 -mdimsi 0 -l 0 -lr 1e-3
python3 main.py -nd 80 -seq 128  -bs 512 -tt 1 -name seq_128_80_label_0 -lff 1 -mdimsi 0 -l 0 -lr 1e-3