#!/bin/bash

#Prepare Dataset for training
#python3 main.py -nd 80 -seq 32 -bs 512 -tt 1 -name seq_32_80_label_2 -lff 0 -mdimsi 0 -l 2 -pds 1
#python3 main.py -nd 80 -seq 64 -bs 512 -tt 1 -name seq_64_80_label_2 -lff 0 -mdimsi 0 -l 2 -pds 1
#python3 main.py -nd 80 -seq 128 -bs 512 -tt 1 -name seq_128_80_label_2 -lff 0 -mdimsi 0 -l 2 -pds 1

#Prepare Dataset for testing
#python3 main.py -nd 80 -seq 32 -bs 512 -tt 1 -name seq_32_80_label_2_test -lff 0 -mdimsi 0 -l 2 -pds 0
#python3 main.py -nd 80 -seq 64 -bs 512 -tt 1 -name seq_64_80_label_2_test -lff 0 -mdimsi 0 -l 2 -pds 0
#python3 main.py -nd 80 -seq 128 -bs 512 -tt 1 -name seq_128_80_label_2_test -lff 0 -mdimsi 0 -l 2 -pds 0

#train the models 80 drives
#python3 main.py -nd 80 -seq 32 -bs 512 -tt 1 -name seq_32_80_label_2 -lff 1 -mdimsi 0 -l 2 -pds 1 -lr 1e-4
#python3 main.py -nd 80 -seq 64 -bs 512 -tt 1 -name seq_64_80_label_2 -lff 1 -mdimsi 0 -l 2 -pds 1 -lr 1e-4
python3 main.py -nd 80 -seq 128 -bs 512 -tt 1 -name seq_128_80_label_2 -lff 1 -mdimsi 0 -l 2 -pds 1 -lr 1e-4