#!/bin/bash
#training all features
python3 main.py -nd 80 -seq 32 -bs 512 -tt 1 -name seq_32_80_label_latency_all_features -lff 1 -mdimsi 0 -l 0 -pds 1 -lr 1e-4 -nf 3
python3 main.py -nd 80 -seq 64 -bs 512 -tt 1 -name seq_64_80_label_latency_all_features -lff 1 -mdimsi 0 -l 0 -pds 1 -lr 1e-4 -nf 3
python3 main.py -nd 80 -seq 128 -bs 512 -tt 1 -name seq_128_80_label_latency_all_features -lff 1 -mdimsi 0 -l 0 -pds 1 -lr 1e-4 -nf 3

python3 main.py -nd 20 -seq 32 -bs 128 -tt 1 -name seq_32_20_label_latency_all_features -lff 1 -mdimsi 0 -l 0 -pds 1 -lr 1e-4 -nf 3
python3 main.py -nd 20 -seq 64 -bs 128 -tt 1 -name seq_64_20_label_latency_all_features -lff 1 -mdimsi 0 -l 0 -pds 1 -lr 1e-4 -nf 3
python3 main.py -nd 20 -seq 128 -bs 128 -tt 1 -name seq_128_20_label_latency_all_features -lff 1 -mdimsi 0 -l 0 -pds 1 -lr 1e-4 -nf 3

#training all features - no gps
python3 main.py -nd 80 -seq 32 -bs 512 -tt 1 -name seq_32_80_label_latency_nogps -lff 1 -mdimsi 0 -l 0 -pds 1 -lr 1e-4 -nf 2
python3 main.py -nd 80 -seq 64 -bs 512 -tt 1 -name seq_64_80_label_latency_nogps -lff 1 -mdimsi 0 -l 0 -pds 1 -lr 1e-4 -nf 2
python3 main.py -nd 80 -seq 128 -bs 512 -tt 1 -name seq_128_80_label_latency_nogps -lff 1 -mdimsi 0 -l 0 -pds 1 -lr 1e-4 -nf 2

python3 main.py -nd 20 -seq 32 -bs 128 -tt 1 -name seq_32_20_label_latency_nogps -lff 1 -mdimsi 0 -l 0 -pds 1 -lr 1e-4 -nf 2
python3 main.py -nd 20 -seq 64 -bs 128 -tt 1 -name seq_64_20_label_latency_nogps -lff 1 -mdimsi 0 -l 0 -pds 1 -lr 1e-4 -nf 2
python3 main.py -nd 20 -seq 128 -bs 128 -tt 1 -name seq_128_20_label_latency_nogps -lff 1 -mdimsi 0 -l 0 -pds 1 -lr 1e-4 -nf 2


#training all features - only rsrp and rsrq
python3 main.py -nd 80 -seq 32 -bs 512 -tt 1 -name seq_32_80_label_latency_rssr -lff 1 -mdimsi 0 -l 0 -pds 1 -lr 1e-4 -nf 1
python3 main.py -nd 80 -seq 64 -bs 512 -tt 1 -name seq_64_80_label_latency_rssr -lff 1 -mdimsi 0 -l 0 -pds 1 -lr 1e-4 -nf 1
python3 main.py -nd 80 -seq 128 -bs 512 -tt 1 -name seq_128_80_label_latency_rssr -lff 1 -mdimsi 0 -l 0 -pds 1 -lr 1e-4 -nf 1

python3 main.py -nd 20 -seq 32 -bs 128 -tt 1 -name seq_32_20_label_latency_rssr -lff 1 -mdimsi 0 -l 0 -pds 1 -lr 1e-4 -nf 1
python3 main.py -nd 20 -seq 64 -bs 128 -tt 1 -name seq_64_20_label_latency_rssr -lff 1 -mdimsi 0 -l 0 -pds 1 -lr 1e-4 -nf 1
python3 main.py -nd 20 -seq 128 -bs 128 -tt 1 -name seq_128_20_label_latency_rssr -lff 1 -mdimsi 0 -l 0 -pds 1 -lr 1e-4 -nf 1


#training all features - only gps
python3 main.py -nd 80 -seq 32 -bs 512 -tt 1 -name seq_32_80_label_latency_gps -lff 1 -mdimsi 0 -l 0 -pds 1 -lr 1e-4 -nf 0
python3 main.py -nd 80 -seq 64 -bs 512 -tt 1 -name seq_64_80_label_latency_gps -lff 1 -mdimsi 0 -l 0 -pds 1 -lr 1e-4 -nf 0
python3 main.py -nd 80 -seq 128 -bs 512 -tt 1 -name seq_128_80_label_latency_gps -lff 1 -mdimsi 0 -l 0 -pds 1 -lr 1e-4 -nf 0

python3 main.py -nd 20 -seq 32 -bs 128 -tt 1 -name seq_32_20_label_latency_gps -lff 1 -mdimsi 0 -l 0 -pds 1 -lr 1e-4 -nf 0
python3 main.py -nd 20 -seq 64 -bs 128 -tt 1 -name seq_64_20_label_latency_gps -lff 1 -mdimsi 0 -l 0 -pds 1 -lr 1e-4 -nf 0
python3 main.py -nd 20 -seq 128 -bs 128 -tt 1 -name seq_128_20_label_latency_gps -lff 1 -mdimsi 0 -l 0 -pds 1 -lr 1e-4 -nf 0

