#!/bin/bash
##Prepare Dataset for training all features
#python3 main.py -nd 20 -seq 32 -bs 512 -tt 1 -name seq_32_20_label_latency_all_features -lff 0 -mdimsi 0 -l 0 -pds 1 -nf 3
#python3 main.py -nd 20 -seq 64 -bs 512 -tt 1 -name seq_64_20_label_latency_all_features -lff 0 -mdimsi 0 -l 0 -pds 1 -nf 3
#python3 main.py -nd 20 -seq 128 -bs 512 -tt 1 -name seq_128_20_label_latency_all_features -lff 0 -mdimsi 0 -l 0 -pds 1 -nf 3
##
python3 main.py -nd 80 -seq 32 -bs 512 -tt 1 -name seq_32_80_label_latency_all_features -lff 0 -mdimsi 0 -l 1 -pds 1 -nf 3
python3 main.py -nd 80 -seq 64 -bs 512 -tt 1 -name seq_64_80_label_latency_all_features -lff 0 -mdimsi 0 -l 1 -pds 1 -nf 3
python3 main.py -nd 80 -seq 128 -bs 512 -tt 1 -name seq_128_80_label_latency_all_features -lff 0 -mdimsi 0 -l 1 -pds 1 -nf 3
##Prepare Dataset for training all features no gps
#python3 main.py -nd 20 -seq 32 -bs 512 -tt 1 -name seq_32_20_label_latency_nogps -lff 0 -mdimsi 0 -l 0 -pds 1 -nf 2
#python3 main.py -nd 20 -seq 64 -bs 512 -tt 1 -name seq_64_20_label_latency_nogps -lff 0 -mdimsi 0 -l 0 -pds 1 -nf 2
#python3 main.py -nd 20 -seq 128 -bs 512 -tt 1 -name seq_128_20_label_latency_nogps -lff 0 -mdimsi 0 -l 0 -pds 1 -nf 2
##
python3 main.py -nd 80 -seq 32 -bs 512 -tt 1 -name seq_32_80_label_latency_nogps -lff 0 -mdimsi 0 -l 1 -pds 1 -nf 2
python3 main.py -nd 80 -seq 64 -bs 512 -tt 1 -name seq_64_80_label_latency_nogps -lff 0 -mdimsi 0 -l 1 -pds 1 -nf 2
python3 main.py -nd 80 -seq 128 -bs 512 -tt 1 -name seq_128_80_label_latency_nogps -lff 0 -mdimsi 0 -l 1 -pds 1 -nf 2
##Prepare Dataset for training rssr only
#python3 main.py -nd 20 -seq 32 -bs 512 -tt 1 -name seq_32_20_label_latency_rssr -lff 0 -mdimsi 0 -l 0 -pds 1 -nf 1
#python3 main.py -nd 20 -seq 64 -bs 512 -tt 1 -name seq_64_20_label_latency_rssr -lff 0 -mdimsi 0 -l 0 -pds 1 -nf 1
#python3 main.py -nd 20 -seq 128 -bs 512 -tt 1 -name seq_128_20_label_latency_rssr -lff 0 -mdimsi 0 -l 0 -pds 1 -nf 1
##
python3 main.py -nd 80 -seq 32 -bs 512 -tt 1 -name seq_32_80_label_latency_rssr -lff 0 -mdimsi 0 -l 1 -pds 1 -nf 1
python3 main.py -nd 80 -seq 64 -bs 512 -tt 1 -name seq_64_80_label_latency_rssr -lff 0 -mdimsi 0 -l 1 -pds 1 -nf 1
python3 main.py -nd 80 -seq 128 -bs 512 -tt 1 -name seq_128_80_label_latency_rssr -lff 0 -mdimsi 0 -l 1 -pds 1 -nf 1
##Prepare Dataset for training gps only
#python3 main.py -nd 20 -seq 32 -bs 512 -tt 1 -name seq_32_20_label_latency_gps -lff 0 -mdimsi 0 -l 0 -pds 1 -nf 0
#python3 main.py -nd 20 -seq 64 -bs 512 -tt 1 -name seq_64_20_label_latency_gps -lff 0 -mdimsi 0 -l 0 -pds 1 -nf 0
#python3 main.py -nd 20 -seq 128 -bs 512 -tt 1 -name seq_128_20_label_latency_gps -lff 0 -mdimsi 0 -l 0 -pds 1 -nf 0
##
python3 main.py -nd 80 -seq 32 -bs 512 -tt 1 -name seq_32_80_label_latency_gps -lff 0 -mdimsi 0 -l 1 -pds 1 -nf 0
python3 main.py -nd 80 -seq 64 -bs 512 -tt 1 -name seq_64_80_label_latency_gps -lff 0 -mdimsi 0 -l 1 -pds 1 -nf 0
python3 main.py -nd 80 -seq 128 -bs 512 -tt 1 -name seq_128_80_label_latency_gps -lff 0 -mdimsi 0 -l 1 -pds 1 -nf 0


#prepare testing dataset
##Prepare Dataset for testing all features
python3 main.py -nd 20 -seq 32 -bs 512 -tt 1 -name seq_32_20_label_latency_allfeatures_test -lff 0 -mdimsi 0 -l 0 -pds 0 -nf 3
python3 main.py -nd 20 -seq 64 -bs 512 -tt 1 -name seq_64_20_label_latency_allfeatures_test -lff 0 -mdimsi 0 -l 0 -pds 0 -nf 3
python3 main.py -nd 20 -seq 128 -bs 512 -tt 1 -name seq_128_20_label_latency_allfeatures_test -lff 0 -mdimsi 0 -l 0 -pds 0 -nf 3

##Prepare Dataset for testing no gps
python3 main.py -nd 20 -seq 32 -bs 512 -tt 1 -name seq_32_20_label_latency_nogps_test -lff 0 -mdimsi 0 -l 0 -pds 0 -nf 2
python3 main.py -nd 20 -seq 64 -bs 512 -tt 1 -name seq_64_20_label_latency_nogps_test -lff 0 -mdimsi 0 -l 0 -pds 0 -nf 2
python3 main.py -nd 20 -seq 128 -bs 512 -tt 1 -name seq_128_20_label_latency_nogps_test -lff 0 -mdimsi 0 -l 0 -pds 0 -nf 2

##Prepare Dataset for testing rsrp and rsrq only
python3 main.py -nd 20 -seq 32 -bs 512 -tt 1 -name seq_32_20_label_latency_rssr_test -lff 0 -mdimsi 0 -l 0 -pds 0 -nf 1
python3 main.py -nd 20 -seq 64 -bs 512 -tt 1 -name seq_64_20_label_latency_rssr_test -lff 0 -mdimsi 0 -l 0 -pds 0 -nf 1
python3 main.py -nd 20 -seq 128 -bs 512 -tt 1 -name seq_128_20_label_latency_rssr_test -lff 0 -mdimsi 0 -l 0 -pds 0 -nf 1

##Prepare Dataset for testing gps only
python3 main.py -nd 20 -seq 32 -bs 512 -tt 1 -name seq_32_20_label_latency_gps_test -lff 0 -mdimsi 0 -l 0 -pds 0 -nf 0
python3 main.py -nd 20 -seq 64 -bs 512 -tt 1 -name seq_64_20_label_latency_gps_test -lff 0 -mdimsi 0 -l 0 -pds 0 -nf 0
python3 main.py -nd 20 -seq 128 -bs 512 -tt 1 -name seq_128_20_label_latency_gps_test -lff 0 -mdimsi 0 -l 0 -pds 0 -nf 0


